{{- if not .Values.frpc.existingSecret }}
{{- if .Values.frpc.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frpc.fullname" . }}
  labels:
    {{- include "frpc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.frpc.existingSecretKey }}: {{ .Values.frpc.auth.token | quote }}
{{- end }}
{{- end }}
